### ISSUE TITLE
Replace "You're invited to join" title to "Matrix user page" title on pages, that links to mxid

### ISSUE THREAD

**Issue by MurzNN** [matrix-org/matrix.to#161]
**Describe the bug**
Now link to my Matrix user at https://matrix.to/#/@murz:ru-matrix.org shows the page with "You're invited to join" title - this looks like invitation for join to some public room or community, instead of some "User info" page.

**Expected behavior**
I know, that "User profiles" is not implemented yet in Matrix, but simply change title "You're invited to join" to something like "Matrix user page" will be much better. And already below we can add some info "Matrix id of this user", and actions buttons like "Start new chat with this user".

**Comment by bmarty** [comment]
Also "accept invite" action is wrong

<img width="557" alt="image" src="https://user-images.githubusercontent.com/3940906/96907174-2baa4e80-149b-11eb-81ce-cd25e1f646d6.png">

**Comment by ludwigbald** [comment]
this one too is fixed with the new matrix.to

**Comment by MadLittleMods** [comment]
This issue is still relevant. The page title (link preview) is still `You're invited to talk on Matrix`

![](https://user-images.githubusercontent.com/558581/134740683-ec7f8275-3c6c-4cee-93d2-e70948503b38.png)

But the action looks better now as `Continue`

![](https://user-images.githubusercontent.com/558581/134740767-b0156728-fa3d-4736-8232-2868baf20879.png)
